### ISSUE TITLE
Verify that all resources created by Mockup-Creator contain a json schema files

### ISSUE THREAD

**Issue by FelixD999** [DMTF/Redfish-JsonSchema-ResponseValidator#10]
Hi,

Thanks for your answer about redfish forum.
[https://redfishforum.com/thread/898/required-properties-json-schema-resource?page=1&scrollTo=3383](url)
Due to the resource of oem schema files also be created in directory specified by Mockup-Creator, some errors will occur when executing the JSON Schema response validator to verify all resources.

Is there a way to judge and skip the json schema file when using this tool to verify the full resource created by Mockup-Creator ?

Thanks,
Felix

**Comment by mraineri** [comment]
At this time, no; the mockup creator was meant to copy every local file in the service to produce an exact copy of the service (including non-Redfish resources).

However, I'd like to understand better how you're making use of the JSON Schema validator. I've normally only seen the tool pointed at single resources/files, so maybe there's a better option for running it against a full mockup.

**Comment by FelixD999** [comment]
I have prepared a folder containing JSON schema files from  specific version in the DSP8010 and some OEM JSON schema files of our own.
Send the following command:
python3 Redfish-JsonSchema-ResponseValidator.py -m {{mockup folder path}} -s {{json schema folder patch}} -v

The completed message is similar to the following:
1115 resources validated.
41 errors. See ./validate_errs
schemas returned from GET   158
schemas returned from cache 957

**Comment by mraineri** [comment]
Thanks. Going over the tool, I think it might be better for the `-m` option to detect if the file is a schema file or resource file, and skip over schema files.
