### ISSUE TITLE
Schema validation against a specified one 

### ISSUE THREAD

**Issue by pradeep-bose** [DMTF/Redfish-JsonSchema-ResponseValidator#8]
I am doing a verbose run as below 

 `$python3 Redfish-JsonSchema-ResponseValidator.py -i /redfish/v1/Systems/1/Memory/ -u user -p password -s ./DMTFSchemas/DMTF/json-schema -r https://192.**.**.** -v`

i get the output as below 

1) The GET request of /redfish/v1/Systems/1/Memory/ URI which is a success and gets listed properly 

2) The schema which it was validated against is MemoryCollection. Why is it not picking Memory.json 
or maybe [Memory.v1_6_0.json](https://redfish.dmtf.org/schemas/Memory.v1_6_0.json) ? 

```
1 resources validated.
0 errors
schemas returned from GET   1
schemas returned from cache 0
```

My schema source is a valid one , contains all the files. 
Is it a bug / some other way to force to pick the json schema provided by user input

**Comment by billdodd** [comment]
I expect you are seeing these results because the resource URI given (/redfish/v1/Systems/1/Memory/) is for a MemoryCollection. If you look at that resource, itprobably looks something like this:

```
{
    "@odata.type": "#MemoryCollection.MemoryCollection",
    "Name": "Memory Module Collection",
    "Members@odata.count": 4,
    "Members": [
        {
            "@odata.id": "/redfish/v1/Systems/437XR1138R2/Memory/DIMM1"
        },
        {
            "@odata.id": "/redfish/v1/Systems/437XR1138R2/Memory/DIMM2"
        },
        {
            "@odata.id": "/redfish/v1/Systems/437XR1138R2/Memory/DIMM3"
        },
        {
            "@odata.id": "/redfish/v1/Systems/437XR1138R2/Memory/DIMM4"
        }
    ],
    "@odata.context": "/redfish/v1/$metadata#MemoryCollection.MemoryCollection",
    "@odata.id": "/redfish/v1/Systems/437XR1138R2/Memory",
    "@Redfish.Copyright": "Copyright 2014-2017 Distributed Management Task Force, Inc. (DMTF). For the full DMTF copyright policy, see http://www.dmtf.org/about/policies/copyright."
}
```

Note in the example above the `@odata.type` property is `#MemoryCollection.MemoryCollection` and it is basically just a `Members` array with a collection of `@odata.id` links to the Memory members.

Given that, you should now be able to validate the individual `Memory` members by specifying each of their URIs in turn. e.g.:

```
python3 Redfish-JsonSchema-ResponseValidator.py -i /redfish/v1/Systems/1/Memory/DIMM1 -u user -p password -s ./DMTFSchemas/DMTF/json-schema -r https://192.**.**.** -v
``` 

Replace `/redfish/v1/Systems/1/Memory/DIMM1` with the actual URI for one of your Memory members. Then repeat for each of the other members.

**Comment by pradeep-bose** [comment]
Thanks @billdodd  , i just saw the code as well and realized the schema name is picked by using the @odata.type property to distinguish it. 
I had created a mess , since i was using the expand query to avoid multiple GET request
https://192.**.**.**/redfish/v1/Systems/1/Memory?$expand=.#

**Comment by pwvancil** [comment]
yes-the current tool uses the @odata.type properety to get the schema namespace and version and either uses DMTF schema location or a local directory store for all schemas.
We have a major update in progress on the tool that will:
1) validate any response against the well-known DMTF schema derived from @odata.type
2) also validate the response against the schema against the schema in JsonSchemas collection for that namespace base on the "Uri" and "PublicationUri" values---noting that PublicationUri might be DMTF
3) and also validate against the schema returned by the Link header
We have seen cases where the @odata.type version on link headers differed and cases where the JsonSchemas Uri is different than Link header and of course PublicationUri can be an oem publication.
The tool will be able to handle local refs  with the update.
Everything is about done except we are also trying the decouple it from MockupCreator
thanks

**Comment by billdodd** [comment]
@pwvancil - thanks for sharing your in-progress work. Sounds like a very nice update!

**Comment by mraineri** [comment]
At this time we're archiving this project in favor of the Redfish Service Validator found here: https://github.com/DMTF/Redfish-Service-Validator
